### ISSUE TITLE
Обновите RSS

### ISSUE THREAD

**Issue by zetroot** [puzanov/keybeard#7]
Нашел вас в castbox. Он берет выпуски видимо из rss фида, а он застрял на 23 выпуске. Бахните еще! 
Офигенный подкаст, молодцы ребята!

**Comment by puzanov** [comment]
этот рсс уже не актуален. подцепиться можно отсюда: https://keybeard.mave.digital/ -- там в списке есть ссылка на рсс фид.

**Comment by zetroot** [comment]
@puzanov спасибо!
